# Generated by Django 5.2 on 2025-04-08 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('department', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamleader_name', models.CharField(max_length=225)),
                ('department', models.CharField(choices=[('AD&DS', 'AI&DS'), ('IT', 'IT'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(choices=[('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year'), ('4 year', '4 year')], max_length=20)),
                ('problem_solution', models.FileField(upload_to='problem_solution/')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem_statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.faculty')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.theme')),
            ],
        ),
    ]
