# Generated by Django 5.2 on 2025-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
