# Generated by Django 5.2 on 2025-04-17 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem.problem_statement'),
            preserve_default=False,
        ),
    ]
